# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI9.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        font = QtGui.QFont()
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(12, 84, 73);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cameraFeed = QtWidgets.QLabel(self.centralwidget)
        self.cameraFeed.setGeometry(QtCore.QRect(320, 50, 1280, 720))
        self.cameraFeed.setStyleSheet("background-color: rgb(80, 80, 80);\n"
"border-color: rgb(0, 0, 0);\n"
"border: 6px solid black;")
        self.cameraFeed.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cameraFeed.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cameraFeed.setLineWidth(1)
        self.cameraFeed.setText("")
        self.cameraFeed.setObjectName("cameraFeed")
        self.captureButton = QtWidgets.QPushButton(self.centralwidget)
        self.captureButton.setGeometry(QtCore.QRect(80, 815, 350, 160))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.captureButton.setFont(font)
        self.captureButton.setStyleSheet("background-color: rgb(255, 204, 51);\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.captureButton.setObjectName("captureButton")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(1490, 815, 350, 160))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.clearButton.setFont(font)
        self.clearButton.setStyleSheet("background-color: rgb(255, 204, 51);\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.clearButton.setObjectName("clearButton")
        self.equationOutput = QtWidgets.QTextBrowser(self.centralwidget)
        self.equationOutput.setGeometry(QtCore.QRect(550, 800, 820, 190))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.equationOutput.setFont(font)
        self.equationOutput.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border: 4px solid black;")
        self.equationOutput.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.equationOutput.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.equationOutput.setTabStopDistance(80.0)
        self.equationOutput.setObjectName("equationOutput")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(550, 1000, 820, 55))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(18)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("color: rgb(245, 240, 207);")
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setLineWidth(0)
        self.textEdit.setObjectName("textEdit")
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(1730, 310, 81, 271))
        self.verticalSlider.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"border: 4px solid black;")
        self.verticalSlider.setStyleSheet(
"QSlider::handle:vertical {"
"background-color: rgb(255, 204, 51);\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius: 8px;"         # Border radius
"}")
        self.verticalSlider.setMaximum(255)
        self.verticalSlider.setSliderPosition(127)
        self.verticalSlider.setTracking(True)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setInvertedAppearance(False)
        self.verticalSlider.setObjectName("verticalSlider")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(1600, 600, 321, 55))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("color: rgb(245, 240, 207);")
        self.textEdit_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(1640, 310, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        self.textEdit_3.setFont(font)
        self.textEdit_3.setStyleSheet("color: rgb(245, 240, 207);")
        self.textEdit_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(1640, 428, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        self.textEdit_4.setFont(font)
        self.textEdit_4.setStyleSheet("color: rgb(245, 240, 207);")
        self.textEdit_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(1665, 545, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        self.textEdit_5.setFont(font)
        self.textEdit_5.setStyleSheet("color: rgb(245, 240, 207);")
        self.textEdit_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_5.setObjectName("textEdit_5")
        self.cameraFeed.raise_()
        self.clearButton.raise_()
        self.equationOutput.raise_()
        self.captureButton.raise_()
        self.textEdit.raise_()
        self.verticalSlider.raise_()
        self.textEdit_2.raise_()
        self.textEdit_3.raise_()
        self.textEdit_4.raise_()
        self.textEdit_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.captureButton.setText(_translate("MainWindow", "Capture Number"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.equationOutput.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:36pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Sans\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">Captured Number</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Sans\'; font-size:18pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">Threshold Value</span></p></body></html>"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Sans\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">255</span></p></body></html>"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Sans\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">127</span></p></body></html>"))
        self.textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Sans\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">0</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
